### ISSUE TITLE
I get error when attempting to run `make start`

### ISSUE THREAD

**Issue by tmli3b3rm4n** [whummer/localstack-demo#3]
```LATLmacK0RJJGH8:localstack-demo-1 tlieberman$ sudo make install
npm install
npm WARN localstack-demo@1.0.0 license should be a valid SPDX license expression

audited 1120 packages in 1.935s
found 5 vulnerabilities (4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
which serverless || npm install -g serverless
/usr/local/bin/serverless
which localstack || pip install localstack
/usr/local/bin/localstack
LATLmacK0RJJGH8:localstack-demo-1 tlieberman$ sudo make start
npm install
npm WARN localstack-demo@1.0.0 license should be a valid SPDX license expression

audited 1120 packages in 1.669s
found 5 vulnerabilities (4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
which serverless || npm install -g serverless
/usr/local/bin/serverless
which localstack || pip install localstack
/usr/local/bin/localstack
Deploying Serverless app to local environment
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: config.stage: local
Serverless: Starting LocalStack in Docker. This can take a while.
Serverless: Checking state of LocalStack container 5a6b01f87c36
Serverless: Checking state of LocalStack container 5a6b01f87c36
Serverless: Checking state of LocalStack container 5a6b01f87c36
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Invoke aws:common:cleanupTempDir
Serverless: [AWS s3 200 0.034s 0 retries] listBuckets({})
Serverless: Creating deployment bucket localstack-test-bucket
Serverless: [AWS s3 404 0.028s 0 retries] headBucket({ Bucket: 'localstack-test-bucket' })
Serverless: Creating deployment bucket 'localstack-test-bucket'...
Serverless: [AWS s3 200 0.02s 0 retries] createBucket({ Bucket: 'localstack-test-bucket',
  ACL: 'private',
  CreateBucketConfiguration: { LocationConstraint: 'us-east-1' } })
Serverless: [AWS s3 200 0.033s 0 retries] createBucket({ Bucket: 'localstack-test-bucket',
  CreateBucketConfiguration: { LocationConstraint: 'us-east-1' } })
Serverless: [AWS s3 200 0.012s 0 retries] headBucket({ Bucket: 'localstack-test-bucket' })
Serverless: [AWS s3 200 0.013s 0 retries] getBucketVersioning({ Bucket: 'localstack-test-bucket' })
Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Skip plugin function AwsCompileFunctions.downloadPackageArtifacts (lambda.mountCode flag is enabled)
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.019s 0 retries] getBucketLocation({ Bucket: 'localstack-test-bucket' })
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.031s 0 retries] describeStacks({ StackName: 'localstack-demo-local' })
Serverless: [AWS s3 200 0.026s 0 retries] listObjectsV2({ Bucket: 'localstack-test-bucket',
  Prefix: 'serverless/localstack-demo/local' })
Serverless: [AWS sts 200 0.02s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.022s 0 retries] putObject({ Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket: 'localstack-test-bucket',
  Key: 'serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'wxqH2W8PsaQQt9sWlSAqL0BnBScVBvTAZxOGHgadV6o=' } })
Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Creating Stack...
Serverless: [AWS cloudformation 500 2.392s 3 retries] createStack({ StackName: 'localstack-demo-local',
  OnFailure: 'ROLLBACK',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-bucket/serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 500 1.302s 3 retries] createStack({ StackName: 'localstack-demo-local',
  OnFailure: 'ROLLBACK',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-bucket/serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 500 1.123s 3 retries] createStack({ StackName: 'localstack-demo-local',
  OnFailure: 'ROLLBACK',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-bucket/serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 500 1.063s 3 retries] createStack({ StackName: 'localstack-demo-local',
  OnFailure: 'ROLLBACK',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-bucket/serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 500 1.219s 3 retries] createStack({ StackName: 'localstack-demo-local',
  OnFailure: 'ROLLBACK',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-bucket/serverless/localstack-demo/local/1572891908282-2019-11-04T18:25:08.282Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
 
  Serverless Error ---------------------------------------
 
  500
 
  Stack Trace --------------------------------------------
 
ServerlessError: 500
    at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:305:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.46.1
 
make: *** [start] Error 1
```

**Comment by whummer** [comment]
Thanks for reporting @tmli3b3rm4n , and apologies for the long delay - this issue completely slipped through the cracks. There have been several changes to LocalStack in the meantime - can you please give it another try with the `latest` version of the Docker image? Please re-open this issue if the problem persists. Thanks!
